"use client";
import "../../globals.css";
import Footer from "../../../../components/Footer";
import HeaderWithMenu from "../../../../components/HeaderWithMenu";
import { jakarta } from "../../../../public/fonts/jakartaFont";
import { useSelector } from "react-redux";

// export const metadata = {
//   title: "Rent Car App",
//   description: "Generated by Mohamad",
// };

export default function RootLayout({ children }) {
  const { darkmode } = useSelector((state) => state.theme);
  console.log(darkmode)
  return (
    <html lang="en" className={`${jakarta.variable} font-sans`}>
      <body className={`${darkmode?"bg-secondinary-dark-900":"bg-[#F6F7F9]"}`}>
        <HeaderWithMenu />
        <div className="w-full flex container mx-auto  max-w-screen-xl flex-col items-center justify-center">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
