"use client";
import { useSelector } from "react-redux";
import ProfileHeader from "../../../components/ProfileHeader";
import ProfileSidebar from "../../../components/ProfileSidebar";
import { jakarta } from "../../../public/fonts/jakartaFont";
import "../globals.css";

// export const metadata = {
//   title: "profile page",
//   description: "Generated by Mohamad",
// };

function ProfileLayout({ children }) {
  const { darkmode } = useSelector((state) => state.theme);
  return (
    <html lang="en" className={`${jakarta.variable} font-sans`}>
      <body className={`${darkmode ? "bg-secondinary-dark-900" : "bg-[#F6F7F9]"}`}>
        <ProfileHeader />
        <div className="w-full flex container mx-auto max-w-screen-xl flex-col items-center justify-center">
          <div className="w-full grid grid-cols-1 md:gap-2 md:grid-cols-5 grid-rows-1">
            <div className={`${darkmode?"bg-secondinary-Default":"bg-primary-white"} hidden md:block rounded-md md:col-span-1`}>
              <ProfileSidebar />
            </div>
            <div className="col-span-1 row-span-1 md:col-span-4 pb-3">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}

export default ProfileLayout;
